cd /srv/apps/mybot
mkdir -p .github/workflows
tee .github/workflows/docker.yml >/dev/null <<'YAML'
name: Build and Push
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/kronser84/burocrat:latest
YAML

git add .github/workflows/docker.yml
git commit -m "fix CI yaml"
git push
